var profs = ["Arts & Crafts",
             "Cloak & Dagger",
             "Faith & Wisdom",
             "Flora & Fauna",
             "Hammer & Nail",
             "Herbs & Sprouts",
             "Hunting & Hideworking",
             "Law & Lore",
             "Mines & Mountains",
             "Sparks & Embers",
             "Stocks & Cultivars",
             "Sugar & Spice",
             "Thread & Needle",
             "Natural Philosophy",
             "Perennial Philosophy"];